Repository vitech-team/mood-feed-test, pull requests merged in 2020-10, with the labels that each got.

#12 chore: fix charts
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
  charts/mood-feed-test/templates/canary.yaml
  charts/mood-feed-test/templates/configmap.yaml
  charts/mood-feed-test/templates/deployment.yaml
  charts/mood-feed-test/templates/hpa.yaml
  charts/mood-feed-test/templates/ingress.yaml
  charts/mood-feed-test/templates/ksvc.yaml
  charts/mood-feed-test/templates/service.yaml
Labels: size/L

#13 chore: fix charts
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
Labels: size/XS

#14 chore: fix charts
  .lighthouse/jenkins-x/release.yaml
Labels: approved, size/XS

#15 chore: test
  .lighthouse/jenkins-x/release.yaml
  charts/mood-feed-test/templates/configmap.yaml
Labels: size/S

#17 chore: check promote
  test/pages/page.ts
Labels: approved, size/XS
